// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe2yhO4OWFOyVNYse1sN1ohwICUMsNh9k',
    appId: '1:366699623911:web:dbd175d7c954c13cd6b942',
    messagingSenderId: '366699623911',
    projectId: 'heynoteapp-ce76e',
    authDomain: 'heynoteapp-ce76e.firebaseapp.com',
    storageBucket: 'heynoteapp-ce76e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6upC59tX4OV2fDRDY2vlCKzGeXDP4VbA',
    appId: '1:366699623911:android:2b3366ff3ca3b96dd6b942',
    messagingSenderId: '366699623911',
    projectId: 'heynoteapp-ce76e',
    storageBucket: 'heynoteapp-ce76e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwHIjOTsh6YcvActb-GbM1BVEZq3VZayU',
    appId: '1:366699623911:ios:967d7aaa3c14690bd6b942',
    messagingSenderId: '366699623911',
    projectId: 'heynoteapp-ce76e',
    storageBucket: 'heynoteapp-ce76e.appspot.com',
    iosBundleId: 'com.example.heynoteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwHIjOTsh6YcvActb-GbM1BVEZq3VZayU',
    appId: '1:366699623911:ios:2531e40384cedd2bd6b942',
    messagingSenderId: '366699623911',
    projectId: 'heynoteapp-ce76e',
    storageBucket: 'heynoteapp-ce76e.appspot.com',
    iosBundleId: 'com.example.heynoteapp.RunnerTests',
  );
}
